# Test your FastAPI endpoints

GET http://127.0.0.1:3001/
Accept: application/json

###

GET http://127.0.0.1:3001/api/users/student/grade
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InN0dWRlbnQiLCJjb2RlIjoiUzAwMiIsIm1haWwiOiJwZXRyb3ZAZXhhbXBsZS5jb20iLCJncm91cCI6Ilx1MDQxM1x1MDQ0MFx1MDQ0M1x1MDQzZlx1MDQzZlx1MDQzMCAyIiwiZXhwIjoxNzMyNTg4NzM5fQ.WmlMkDlI7P2B8gd84Mk9OscD4IhVZqHlakZWRei-h1s

###

GET http://127.0.0.1:3001/api/users/teacher/all/grades
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlYWNoZXIiLCJjb2RlIjoiMjdcdTA0M2NcdTA0MzJcdTA0NDA0NSIsIm1haWwiOiIyMTQ2Mzc2QGdtYWlsLmNvbSIsImV4cCI6MTczMjU4NDE0Nn0.OhaPgbNEbC4gwXbr6Z4-nBVv3B2_KuXx9BKcfnkt_7E

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:3001/api/users/teacher/info
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlYWNoZXIiLCJjb2RlIjoiMjdcdTA0M2NcdTA0MzJcdTA0NDA0NSIsIm1haWwiOiIyMTQ2Mzc2QGdtYWlsLmNvbSIsImV4cCI6MTczMjU4NDE0Nn0.OhaPgbNEbC4gwXbr6Z4-nBVv3B2_KuXx9BKcfnkt_7E

###

GET http://127.0.0.1:3001/neutral/entrances
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN0dWRlbnQiLCJjb2RlIjoiUzAwMSIsIm1haWwiOiJpdmFub3ZAZXhhbXBsZS5jb20iLCJncm91cCI6Ilx1MDQxM1x1MDQ0MFx1MDQ0M1x1MDQzZlx1MDQzZlx1MDQzMCAxIiwiZXhwIjoxNzMyMjIxMDU0fQ.rE6LDaxD35-kuszZS-R5DVhcrz1wAielflaMbFPV5pU

###

GET http://127.0.0.1:3001/neutral/lesson/1
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN0dWRlbnQiLCJjb2RlIjoiUzAwMSIsIm1haWwiOiJpdmFub3ZAZXhhbXBsZS5jb20iLCJncm91cCI6Ilx1MDQxM1x1MDQ0MFx1MDQ0M1x1MDQzZlx1MDQzZlx1MDQzMCAxIiwiZXhwIjoxNzMyMjIxMDU0fQ.rE6LDaxD35-kuszZS-R5DVhcrz1wAielflaMbFPV5pU

###

GET http://127.0.0.1:3001/teacher/disciplines
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlYWNoZXIiLCJjb2RlIjoiMjdcdTA0M2NcdTA0MzJcdTA0NDA0NSIsIm1haWwiOiIyMTQ2Mzc2QGdtYWlsLmNvbSIsImV4cCI6MTczMjI4ODE3Mn0._3sbANU5Vxm4TWTCd7V7Q6XtGwxpbPQxBKuIUNCRKnc

###

GET http://127.0.0.1:3001/api/users/teacher/lessons
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlYWNoZXIiLCJjb2RlIjoiMjdcdTA0M2NcdTA0MzJcdTA0NDA0NSIsIm1haWwiOiIyMTQ2Mzc2QGdtYWlsLmNvbSIsImV4cCI6MTczMjU3ODY4M30.aq50V4RApRAS5dJljzVnaI-WKCTwka16F1omY_eLMjs

###

POST http://127.0.0.1:3001/teacher/mark
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlYWNoZXIiLCJjb2RlIjoiMjdcdTA0M2NcdTA0MzJcdTA0NDA0NSIsIm1haWwiOiIyMTQ2Mzc2QGdtYWlsLmNvbSIsImV4cCI6MTczMjIyMzcxNn0.uPCDZe8hOd9GxvJAyzz4m1nh6A-Z0SP1_QOyuY3lL-o

{
  "lesson_id": 1,
  "student_id": 1,
  "mark": 5
}

###

GET http://127.0.0.1:3001/teacher/lessons
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlYWNoZXIiLCJjb2RlIjoiMjdcdTA0M2NcdTA0MzJcdTA0NDA0NSIsIm1haWwiOiIyMTQ2Mzc2QGdtYWlsLmNvbSIsImV4cCI6MTczMjIyMzcxNn0.uPCDZe8hOd9GxvJAyzz4m1nh6A-Z0SP1_QOyuY3lL-o


###

GET http://127.0.0.1:3001/api/users/student/lessons
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InN0dWRlbnQiLCJjb2RlIjoiUzAwMiIsIm1haWwiOiJwZXRyb3ZAZXhhbXBsZS5jb20iLCJncm91cCI6Ilx1MDQxM1x1MDQ0MFx1MDQ0M1x1MDQzZlx1MDQzZlx1MDQzMCAyIiwiZXhwIjoxNzMyNDEyNDA1fQ.OiXuKrpee8_e-EC9UzZJA7nqrgUPiHC0OgyHgBR3AB8

###

GET http://127.0.0.1:3001/teacher/groups
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlYWNoZXIiLCJjb2RlIjoiMjdcdTA0M2NcdTA0MzJcdTA0NDA0NSIsIm1haWwiOiIyMTQ2Mzc2QGdtYWlsLmNvbSIsImV4cCI6MTczMjIyMzcxNn0.uPCDZe8hOd9GxvJAyzz4m1nh6A-Z0SP1_QOyuY3lL-o

###

POST http://127.0.0.1:3001/teacher/marking/students
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlYWNoZXIiLCJjb2RlIjoiMjdcdTA0M2NcdTA0MzJcdTA0NDA0NSIsIm1haWwiOiIyMTQ2Mzc2QGdtYWlsLmNvbSIsImV4cCI6MTczMjIyMzcxNn0.uPCDZe8hOd9GxvJAyzz4m1nh6A-Z0SP1_QOyuY3lL-o

{
  "lesson_id": 1,
  "students": {"1": true, "2": false}
}

###

POST http://127.0.0.1:3001/neutral/enter/exit
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlN3ZWV0Iiwic2Vjb25kbmFtZSI6IkFzcyIsImxhc3RuYW1lIjoiTG92ZSIsInJvbGVfaWQiOjIsImNvZGUiOiIyN9C80LLRgDQ1IiwiaWF0IjoxNzMyMzE1MjQxLCJleHAiOjE3NjM4NTEyNDF9.V6s_kHIEhJbf_pCxgz4EAsf3MyPJTMiy5RPkAS-2l5A

{
  "branch_id": 2,
  "status": "выход",
  "time": "2024-11-21 20:29:50.000000"
}

###

GET http://127.0.0.1:3001/neutral/entrances
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN0dWRlbnQiLCJjb2RlIjoiUzAwMSIsIm1haWwiOiJpdmFub3ZAZXhhbXBsZS5jb20iLCJncm91cCI6Ilx1MDQxM1x1MDQ0MFx1MDQ0M1x1MDQzZlx1MDQzZlx1MDQzMCAxIiwiZXhwIjoxNzMyMjg2NzA1fQ.zHIqEn1elIgIErdbEPVAZCVJ7oJ7javymS3f-KUAD6E

###

GET http://127.0.0.1:3001/neutral/enter/token
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlYWNoZXIiLCJjb2RlIjoiMjdcdTA0M2NcdTA0MzJcdTA0NDA0NSIsIm1haWwiOiIyMTQ2Mzc2QGdtYWlsLmNvbSIsImV4cCI6MTczMjMyNTQ1OX0.BOlZA_21Wes-cqziQ7XUdtaLjs7JaJqaX8KZ9vMat88

###

GET http://127.0.0.1:3001/api/users/student/gpa
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InN0dWRlbnQiLCJjb2RlIjoiUzAwMiIsIm1haWwiOiJwZXRyb3ZAZXhhbXBsZS5jb20iLCJncm91cCI6Ilx1MDQxM1x1MDQ0MFx1MDQ0M1x1MDQzZlx1MDQzZlx1MDQzMCAyIiwiZXhwIjoxNzMyNjM5MjQ5fQ.pt5UqjlhnN8YxdCfaSS4QDVfUDeycarrrQ_VK7DaXRs

###

GET http://127.0.0.1:3001/api/users/student/percentile
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InN0dWRlbnQiLCJjb2RlIjoiUzAwMiIsIm1haWwiOiJwZXRyb3ZAZXhhbXBsZS5jb20iLCJncm91cCI6Ilx1MDQxM1x1MDQ0MFx1MDQ0M1x1MDQzZlx1MDQzZlx1MDQzMCAyIiwiZXhwIjoxNzMyNDkyNDMyfQ.uyvQmII0Eea2xCLrM9uUiy39aWE9L__V3qRbc6T3qfs

###

POST http://127.0.0.1:3001/api/users/student/add/custom/lesson
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN0dWRlbnQiLCJjb2RlIjoiUzAwMSIsIm1haWwiOiJpdmFub3ZAZXhhbXBsZS5jb20iLCJncm91cCI6Ilx1MDQxM1x1MDQ0MFx1MDQ0M1x1MDQzZlx1MDQzZlx1MDQzMCAxIiwiZXhwIjoxNzMyNTc5MjkyfQ.TwBWjdA7RagoVZw6rVbsFuf2J2FLdnuFUxgNa8RHmsI

{
  "name": "Плясание на реке Угре",
  "auditory_id": null,
  "start_time": "2024-11-25 14:00:00.000000",
  "end_time": "2024-11-25 15:00:00.000000"
}

###

GET http://127.0.0.1:3001/api/users/student/custom/lessons
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN0dWRlbnQiLCJjb2RlIjoiUzAwMSIsIm1haWwiOiJpdmFub3ZAZXhhbXBsZS5jb20iLCJncm91cCI6Ilx1MDQxM1x1MDQ0MFx1MDQ0M1x1MDQzZlx1MDQzZlx1MDQzMCAxIiwiZXhwIjoxNzMyNTc5MjkyfQ.TwBWjdA7RagoVZw6rVbsFuf2J2FLdnuFUxgNa8RHmsI
